<?php

function ccc_bs_preprocess_page(&$variables) {
  $variables['facebook'] = theme_get_setting('facebook');
  $variables['twitter'] = theme_get_setting('twitter');
  $variables['youtube'] = theme_get_setting('youtube');
  $variables['googleplus'] = theme_get_setting('googleplus');
  $variables['linkedin'] = theme_get_setting('linkedin');
  $variables['pinterest'] = theme_get_setting('pinterest');
  $variables['instagram'] = theme_get_setting('instagram');
}

function ccc_bs_preprocess_html(&$variables) {
  // Add node id to the body class.
  $node = \Drupal::routeMatch()->getParameter('node');
  if($node) {
    $variables['attributes']['class'][] = 'node-' . $node->id();
  }
}